using System;
using System.Collections;
using System.IO;
using Area51.Module;
using Area51.Module.Bot.Local;
using Area51.Module.Exploit;
using Area51.Module.Exploit.Photon_Exploit;
using Area51.Module.Movement;
using Area51.Module.Player;
using Area51.Module.Safety;
using Area51.Module.Safety.Avatar;
using Area51.Module.Safety.Photon;
using Area51.Module.Settings.Logging;
using Area51.Module.Settings.Preformance;
using Area51.Module.Settings.Render;
using Area51.Module.Settings.Theme;
using Area51.Module.TargetMenu;
using Area51.Module.TargetMenu.Murder4_Settings;
using Area51.Module.TargetMenu.World_Hacks.AmongUs_Settings;
using Area51.Module.TargetMenu.World_Hacks.battledisc;
using Area51.Module.TargetMenu.World_Hacks.JustB;
using Area51.Module.World;
using Area51.Module.World.World_Hacks;
using Area51.Module.World.World_Hacks.Among_Us;
using Area51.Module.World.World_Hacks.Just_B;
using Area51.Module.World.World_Hacks.MovieNChill;
using Area51.Module.World.World_Hacks.movmC;
using Area51.Module.World.World_Hacks.Murder_4;
using Area51.Module.World.World_Hacks.sov;
using Area51.Module.World.World_Hacks.sovren;
using Area51.Module.World.World_Hacks.todtartget;
using Area51.Modules.Exploits;
using Area51.SDK.ButtonAPI;
using Area51.SDK.Security;
using MelonLoader;
using UnityEngine;
using VRC.Core;

namespace Area51.SDK
{
	internal class MenuUI
	{
		public static IEnumerator StartUI()
		{
			Console.Title = "Area 51 Private Client | User: " + APIUser.CurrentUser.displayName;
			Main.Instance.QuickMenuStuff = new Alien();
			QMTab qMTab = new QMTab("Area 51 Client", "", "What's a client!", ButtonIcons.PlayerMenu);
			Alien.Spacer(qMTab.menuTransform);
			Main.Instance.WorldButton = new QMNestedButton(qMTab.menuTransform, "World", ButtonIcons.WorldMenu);
			Main.Instance.PlayerButton = new QMNestedButton(qMTab.menuTransform, "Player", ButtonIcons.PlayerMenu);
			Main.Instance.MovementButton = new QMNestedButton(qMTab.menuTransform, "Movement", ButtonIcons.MovementMenu);
			Main.Instance.ExploistButton = new QMNestedButton(qMTab.menuTransform, "Exploits", ButtonIcons.ExploitMenu);
			Main.Instance.Eventexploitbutton = new QMNestedButton(Main.Instance.ExploistButton.menuTransform, "Event Exploits", ButtonIcons.SafetyMenu);
			Main.Instance.Avatarexploitbutton = new QMNestedButton(Main.Instance.ExploistButton.menuTransform, "Avatar Exploits", ButtonIcons.PlayerMenu);
			Main.Instance.SafetyButton = new QMNestedButton(qMTab.menuTransform, "Safety", ButtonIcons.SafetyMenu);
			Main.Instance.Networkbutton = new QMNestedButton(Main.Instance.SafetyButton.menuTransform, "Network Saftey", ButtonIcons.SafetyMenu);
			Main.Instance.Avatarbutton = new QMNestedButton(Main.Instance.SafetyButton.menuTransform, "Avatar Saftey", ButtonIcons.SafetyMenu);
			Main.Instance.BotButton = new QMNestedButton(qMTab.menuTransform, "Bot", ButtonIcons.TheBotsIcon);
			Main.Instance.Privatebotbutton = new QMNestedButton(Main.Instance.BotButton.menuTransform, "Local handler", ButtonIcons.PlayerMenu);
			Main.Instance.GameCheatsMenu = new QMNestedButton(qMTab.menuTransform, "GameCheats", ButtonIcons.GameCheatsMenu);
			Main.Instance.udonexploitbutton = new QMNestedButton(Main.Instance.GameCheatsMenu.menuTransform, "Area-51 Engine", ButtonIcons.Area51EngineMenu);
			Main.Instance.Amongusbutton = new QMNestedButton(Main.Instance.GameCheatsMenu.menuTransform, "Among Us", ButtonIcons.AmongUsMenu);
			Main.Instance.Murderbutton = new QMNestedButton(Main.Instance.GameCheatsMenu.menuTransform, "Murder 4", ButtonIcons.Muder4Menu);
			Main.Instance.Justbbutton = new QMNestedButton(Main.Instance.GameCheatsMenu.menuTransform, "Just B", ButtonIcons.JustBMenu);
			Main.Instance.JustBRoomsbutton = new QMNestedButton(Main.Instance.Justbbutton.menuTransform, "Rooms", ButtonIcons.JustBMenu);
			Main.Instance.Justhbutton = new QMNestedButton(Main.Instance.GameCheatsMenu.menuTransform, "Just H", ButtonIcons.JustHMenu);
			Main.Instance.MovienChill = new QMNestedButton(Main.Instance.GameCheatsMenu.menuTransform, "Movie N Chill", ButtonIcons.MovieNChillMenu);
			Main.Instance.sovren = new QMNestedButton(Main.Instance.GameCheatsMenu.menuTransform, "Sovren's", ButtonIcons.SovernsHomeMenu);
			Main.Instance.SettingsButton = new QMNestedButton(qMTab.menuTransform, "Settings", ButtonIcons.SettingMenu);
			Main.Instance.SettingsButtonpreformance = new QMNestedButton(Main.Instance.SettingsButton.menuTransform, "Performance", ButtonIcons.RocketIcon);
			Main.Instance.SettingsButtonrender = new QMNestedButton(Main.Instance.SettingsButton.menuTransform, "Render", ButtonIcons.RenderIcon);
			Main.Instance.SettingsButtonLoggging = new QMNestedButton(Main.Instance.SettingsButton.menuTransform, "Logging", ButtonIcons.LogsIcon);
			Main.Instance.SettingsButtonTheme = new QMNestedButton(Main.Instance.SettingsButton.menuTransform, "Theme", ButtonIcons.PlayerMenu);
			Main.Instance.Targetbutton = new QMNestedButton(Main.Instance.QuickMenuStuff.SelectedUserMenuQM.transform.Find("ScrollRect/Viewport/VerticalLayoutGroup/Buttons_UserActions/").transform, "Area51", ButtonIcons.PlayerMenu);
			Main.Instance.WorldhacksTargetButton = new QMNestedButton(Main.Instance.Targetbutton.menuTransform, "World Exploits", ButtonIcons.WorldMenu);
			Main.Instance.MurderSettings = new QMNestedButton(Main.Instance.WorldhacksTargetButton.menuTransform, "Murder 4 Menu", ButtonIcons.Muder4Menu);
			Main.Instance.AmongUsSettings = new QMNestedButton(Main.Instance.WorldhacksTargetButton.menuTransform, "Among Us Menu", ButtonIcons.AmongUsMenu);
			Main.Instance.JubstBSettings = new QMNestedButton(Main.Instance.WorldhacksTargetButton.menuTransform, "Just B Menu", ButtonIcons.JustBMenu);
			Main.Instance.BattleDisc = new QMNestedButton(Main.Instance.WorldhacksTargetButton.menuTransform, "Battle Disc Menu", ButtonIcons.RocketIcon);
			Main.Instance.sovrenTarget = new QMNestedButton(Main.Instance.WorldhacksTargetButton.menuTransform, "Sovren's Menu", ButtonIcons.SovernsHomeMenu);
			Main.Instance.TruDareTarget = new QMNestedButton(Main.Instance.WorldhacksTargetButton.menuTransform, "True / Dare", ButtonIcons.SovernsHomeMenu);
			Main.Instance.MovienChillTarget = new QMNestedButton(Main.Instance.WorldhacksTargetButton.menuTransform, "Movie N Chills's Menu", ButtonIcons.MovieNChillMenu);
			Main.Instance.Modules.Add(new JoinByID());
			Main.Instance.Modules.Add(new Rejoin());
			Main.Instance.Modules.Add(new CopyWID());
			Main.Instance.Modules.Add(new InstanceLock());
			Main.Instance.Modules.Add(new FreezeItems());
			Main.Instance.Modules.Add(new ForcePickups());
			Main.Instance.Modules.Add(new TPPeople());
			Main.Instance.Modules.Add(new BlindPeople());
			Main.Instance.Modules.Add(new EliteSpoof());
			Main.Instance.Modules.Add(new CreatorSpoof());
			Main.Instance.Modules.Add(new Room1());
			Main.Instance.Modules.Add(new Room2());
			Main.Instance.Modules.Add(new Room3());
			Main.Instance.Modules.Add(new Room4());
			Main.Instance.Modules.Add(new Room5());
			Main.Instance.Modules.Add(new Room6());
			Main.Instance.Modules.Add(new Room7());
			Main.Instance.Modules.Add(new EnableRooms());
			Main.Instance.Modules.Add(new MurderAssign());
			Main.Instance.Modules.Add(new DetectiveAssign());
			Main.Instance.Modules.Add(new StartGame());
			Main.Instance.Modules.Add(new AbortGame());
			Main.Instance.Modules.Add(new BystanderWin());
			Main.Instance.Modules.Add(new MurderWin());
			Main.Instance.Modules.Add(new KillAll());
			Main.Instance.Modules.Add(new KillLoop());
			Main.Instance.Modules.Add(new BlindAll());
			Main.Instance.Modules.Add(new FlashLoop());
			Main.Instance.Modules.Add(new ForcePickup());
			Main.Instance.Modules.Add(new BringKnife());
			Main.Instance.Modules.Add(new BringRevolver());
			Main.Instance.Modules.Add(new LockDoors());
			Main.Instance.Modules.Add(new OpenDoors());
			Main.Instance.Modules.Add(new A_StartGame());
			Main.Instance.Modules.Add(new A_AbortGame());
			Main.Instance.Modules.Add(new A_MurderWin());
			Main.Instance.Modules.Add(new A_BystandersWin());
			Main.Instance.Modules.Add(new A_CallMeeting());
			Main.Instance.Modules.Add(new A_ReportBody());
			Main.Instance.Modules.Add(new A_CloseVote());
			Main.Instance.Modules.Add(new A_SkipVote());
			Main.Instance.Modules.Add(new A_KillAll());
			Main.Instance.Modules.Add(new A_TaskDone());
			Main.Instance.Modules.Add(new A_AssignImposter());
			Main.Instance.Modules.Add(new A_AssignCrew());
			Main.Instance.Modules.Add(new TPSEveryone());
			Main.Instance.Modules.Add(new MTPEveryone());
			Main.Instance.Modules.Add(new GetUdonEventList());
			Main.Instance.Modules.Add(new CustomUdonEvent());
			Main.Instance.Modules.Add(new UdonExploitFinder());
			Main.Instance.Modules.Add(new NameSpoofer());
			Main.Instance.Modules.Add(new AvatarID());
			Main.Instance.Modules.Add(new FPSUnlocker());
			Main.Instance.Modules.Add(new LoudMic());
			Main.Instance.Modules.Add(new HeadFlipper());
			Main.Instance.Modules.Add(new CopyUserID());
			Main.Instance.Modules.Add(new HideSelf());
			Main.Instance.Modules.Add(new DrippedOut());
			Main.Instance.Modules.Add(new PersonalMirror());
			Main.Instance.Modules.Add(new Speed());
			Main.Instance.Modules.Add(new Fly());
			Main.Instance.Modules.Add(new InfinityJump());
			Main.Instance.Modules.Add(new USpeakEarRape());
			Main.Instance.Modules.Add(new Freecam());
			Main.Instance.Modules.Add(new ItemLag());
			Main.Instance.Modules.Add(new FakeLag());
			Main.Instance.Modules.Add(new FakeLagMic());
			Main.Instance.Modules.Add(new FreezePlayers());
			Main.Instance.Modules.Add(new AudioCrash());
			Main.Instance.Modules.Add(new VoidBypass());
			Main.Instance.Modules.Add(new CorreuptPC());
			Main.Instance.Modules.Add(new AssetBundleCrash());
			Main.Instance.Modules.Add(new GameClose());
			Main.Instance.Modules.Add(new QuestCrash());
			Main.Instance.Modules.Add(new VRCA());
			Main.Instance.Modules.Add(new VRCW());
			Main.Instance.Modules.Add(new PhotonProtection());
			Main.Instance.Modules.Add(new AntiUdon());
			Main.Instance.Modules.Add(new AntiRPC());
			Main.Instance.Modules.Add(new AntiMesh());
			Main.Instance.Modules.Add(new AntiShader());
			Main.Instance.Modules.Add(new AntiCloth());
			Main.Instance.Modules.Add(new AntiAudio());
			Main.Instance.Modules.Add(new AntiBones());
			Main.Instance.Modules.Add(new AntiAnimators());
			Main.Instance.Modules.Add(new AntiColliders());
			Main.Instance.Modules.Add(new AntiLight());
			Main.Instance.Modules.Add(new AntiParticles());
			Main.Instance.Modules.Add(new AntiMatirials());
			Main.Instance.Modules.Add(new CuddleBot1());
			Main.Instance.Modules.Add(new CuddleBot2());
			Main.Instance.Modules.Add(new KIllBots());
			Main.Instance.Modules.Add(new OPSendLogger());
			Main.Instance.Modules.Add(new AssetBundleLogger());
			Main.Instance.Modules.Add(new AvatarLogger());
			Main.Instance.Modules.Add(new VCRALogger());
			Main.Instance.Modules.Add(new UdonLogger());
			Main.Instance.Modules.Add(new EventLogger());
			Main.Instance.Modules.Add(new RpcLogger());
			Main.Instance.Modules.Add(new UnityLogger());
			Main.Instance.Modules.Add(new JoinLogger());
			Main.Instance.Modules.Add(new KeyBinds());
			Main.Instance.Modules.Add(new Clippingfix());
			Main.Instance.Modules.Add(new HideVideoPlayers());
			Main.Instance.Modules.Add(new HideChairs());
			Main.Instance.Modules.Add(new HidePickUps());
			Main.Instance.Modules.Add(new RestartAndRejoin());
			Main.Instance.Modules.Add(new ConsoleClear());
			Main.Instance.Modules.Add(new QuickRestart());
			Main.Instance.Modules.Add(new Logout());
			Main.Instance.Modules.Add(new PlayerList());
			Main.Instance.Modules.Add(new DebugLog());
			Main.Instance.Modules.Add(new CustomNameplates());
			Main.Instance.Modules.Add(new ClockSettings());
			Main.Instance.Modules.Add(new BlockedPlayers());
			Main.Instance.Modules.Add(new TriggerESP());
			Main.Instance.Modules.Add(new ObjectESP());
			Main.Instance.Modules.Add(new CapsuleEsp());
			Main.Instance.Modules.Add(new AlienTheme());
			Main.Instance.Modules.Add(new RetroTheme());
			Main.Instance.Modules.Add(new munchen());
			Main.Instance.Modules.Add(new CustomBGImage());
			Main.Instance.Modules.Add(new ButtonsGreen());
			Main.Instance.Modules.Add(new ButtonsBlue());
			Main.Instance.Modules.Add(new ButtonsRed());
			Main.Instance.Modules.Add(new ButtonsMagenta());
			Main.Instance.Modules.Add(new AvatSelected());
			Main.Instance.Modules.Add(new DownloadVRCSelected());
			Main.Instance.Modules.Add(new ForceClone());
			Main.Instance.Modules.Add(new Tel2User());
			Main.Instance.Modules.Add(new UserIDSelected());
			Main.Instance.Modules.Add(new TargetOrbitch());
			Main.Instance.Modules.Add(new VoiceIM());
			Main.Instance.Modules.Add(new SendEvent());
			Main.Instance.Modules.Add(new ForceSpawnBD());
			Main.Instance.Modules.Add(new LockPlayerMovement());
			Main.Instance.Modules.Add(new ForceRespawn());
			Main.Instance.Modules.Add(new AssignImposter());
			Main.Instance.Modules.Add(new AssignCrew());
			Main.Instance.Modules.Add(new AForceSpawn());
			Main.Instance.Modules.Add(new AmongUsKill());
			Main.Instance.Modules.Add(new MurderAssignTarget());
			Main.Instance.Modules.Add(new DetectiveAssignTarget());
			Main.Instance.Modules.Add(new BystanderAssignTarget());
			Main.Instance.Modules.Add(new KillLoopTarget());
			Main.Instance.Modules.Add(new MurderKillTarget());
			Main.Instance.Modules.Add(new BlindTarget());
			Main.Instance.Modules.Add(new BlindLoopTarget());
			Main.Instance.Modules.Add(new BringItemsTarget());
			Main.Instance.Modules.Add(new BringKnifeTarget());
			Main.Instance.Modules.Add(new BringRevolverTarget());
			Main.Instance.Modules.Add(new ForceSpawn());
			Main.Instance.Modules.Add(new TargetSovrenTP());
			Main.Instance.Modules.Add(new TargetTODTP());
			Main.Instance.Modules.Add(new TargetMovCTP());
			MelonCoroutines.Start(Area51Console.Start());
			foreach (BaseModule module in Main.Instance.Modules)
			{
				module.OnUIInit();
			}
			try
			{
				AlienMisc.Pasteit();
				Alien.Carousel_Banners(state: false);
			}
			catch
			{
			}
			Alien.QM_Text("Area51 - QuickMenu");
			Console.Clear();
			LogHandler.DisplayLogo();
	
			yield return new WaitForSecondsRealtime(0.02f);
		}
	}
}
